"""``envcheck init``: draft an envcheck.yaml from files already in the repo.

Every detection is reported back so nothing is guessed silently.
"""

from __future__ import annotations

import json
import re
import tomllib
from pathlib import Path
from typing import Any

import yaml

from envcheck.context import parse_dotenv

_IMAGE_TYPES = {"postgres": ("postgres", 5432), "redis": ("redis", 6379)}


def _python_constraint(requires: str) -> str | None:
    match = re.search(r">=\s*(\d+\.\d+)", requires)
    return f">={match.group(1)}" if match else None


def detect(root: Path) -> tuple[dict[str, Any], list[str]]:
    config: dict[str, Any] = {"version": 1, "tools": {}}
    notes: list[str] = []

    pyproject = root / "pyproject.toml"
    if pyproject.is_file():
        data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        requires = data.get("project", {}).get("requires-python", "")
        constraint = _python_constraint(requires) if requires else None
        config["tools"]["python"] = constraint or "*"
        notes.append(f"pyproject.toml -> python {constraint or '(any version)'}")
        if (root / "uv.lock").is_file():
            config["tools"]["uv"] = "*"
            notes.append("uv.lock -> uv")

    package = root / "package.json"
    if package.is_file():
        engines = json.loads(package.read_text(encoding="utf-8")).get("engines", {})
        config["tools"]["node"] = engines.get("node", "*")
        notes.append(f"package.json -> node {engines.get('node', '(any version)')}")

    compose = next(
        (
            root / n
            for n in ("docker-compose.yml", "docker-compose.yaml", "compose.yaml", "compose.yml")
            if (root / n).is_file()
        ),
        None,
    )
    if compose is not None:
        config["tools"]["docker"] = "*"
        config["tools"]["docker compose"] = "*"
        config["docker_daemon"] = True
        notes.append(f"{compose.name} -> docker, docker compose, running daemon")
        services = (yaml.safe_load(compose.read_text(encoding="utf-8")) or {}).get("services", {}) or {}
        found: dict[str, Any] = {}
        for name, svc in services.items():
            image = str((svc or {}).get("image", ""))
            for key, (stype, default_port) in _IMAGE_TYPES.items():
                if image.split("/")[-1].startswith(key):
                    port = default_port
                    for mapping in (svc or {}).get("ports", []) or []:
                        parts = str(mapping).split(":")
                        if len(parts) >= 2 and parts[-1].split("/")[0] == str(default_port):
                            port = int(parts[-2])
                    found[name] = {"type": stype, "host": "localhost", "port": port}
                    notes.append(f"{compose.name}: service {name!r} ({image}) -> {stype} on localhost:{port}")
        if found:
            config["services"] = found

    example = root / ".env.example"
    if example.is_file():
        keys = sorted(parse_dotenv(example.read_text(encoding="utf-8")))
        config["env"] = {"required": keys, "drift": {"example": ".env.example", "actual": ".env"}}
        notes.append(f".env.example -> {len(keys)} required variables + drift check")

    if (root / "Makefile").is_file():
        config["tools"]["make"] = "*"
        notes.append("Makefile -> make")

    if not config["tools"]:
        del config["tools"]
    return config, notes


def render(config: dict[str, Any]) -> str:
    header = "# Generated by `envcheck init`. Review it: detection is heuristic.\n"
    return header + yaml.safe_dump(config, sort_keys=False, default_flow_style=False)
